server:
  port: 8082
  servlet:
    context-path: /

spring:
  application:
    name: aggregation-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    url: jdbc:postgresql://postgres:5432/finpulse
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  redis:
    host: redis
    port: 6379
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: aggregation-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.aggregationservice.dto,com.example.*"
        spring.json.type.mapping: userRegisteredEvent:com.example.aggregationservice.dto.UserRegisteredEvent
    properties:
      spring.json.trusted.packages: "com.example.aggregationservice.dto,com.example.*"
  cloud:
    stream:
      bindings:
        userRegistered-in-0:
          destination: user-registered-topic
          group: aggregation-service

encryption:
  secret-key: "2C9KrwifASfYC67m"

bank:
  api:
    banks:
      vbank:
        base-url: https://vbank.open.bankingapi.ru
        client-id: ${VBANK_CLIENT_ID:team214}
        client-secret: ${VBANK_CLIENT_SECRET:hk3EA0lgqWelO7P1gYSnyqCY3zNmez3r}
        token-endpoint: /auth/bank-token
        token-ttl-hours: 24
      abank:
        base-url: https://abank.open.bankingapi.ru
        client-id: ${ABANK_CLIENT_ID:team214}
        client-secret: ${ABANK_CLIENT_SECRET:hk3EA0lgqWelO7P1gYSnyqCY3zNmez3r}
        token-endpoint: /auth/bank-token
        token-ttl-hours: 24
      sbank:
        base-url: https://sbank.open.bankingapi.ru
        client-id: ${SBANK_CLIENT_ID:team214}
        client-secret: ${SBANK_CLIENT_SECRET:hk3EA0lgqWelO7P1gYSnyqCY3zNmez3r}
        token-endpoint: /auth/bank-token
        token-ttl-hours: 24

notification:
  service:
    url: http://notificationservice:8084
user:
  service:
    url: http://userservice:8081

app:
  scheduling:
    transaction-export:
      groups:
        - name: GROUP_00_06
          cron: "0 30 2 * * ?"
        - name: GROUP_06_12
          cron: "0 30 6 * * ?"
        - name: GROUP_12_18
          cron: "0 30 12 * * ?"
        - name: GROUP_18_00
          cron: "0 30 18 * * ?"
      ml-analysis:
        cron: "0 0 23 ? * SUN"

logging:
  level:
    com.example.aggregationservice: DEBUG
    org.springframework.web.client: DEBUG

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic